import type { ChalkInstance } from "chalk";
import type { ColorInformation } from "../types/color.js";
import type { SettingFields } from "../types/settings.js";
import type { LogLevel } from "../types/utils.js";
import chalk from "chalk";

export const TILE_SIZE = 1000 as const;

export const DATA_FOLDER = "database" as const;

export const UPLOADS_FOLDER = "uploads" as const;

export const DATABASE_NAME = "data.db" as const;

export const SETTINGS_FILE_NAME = "settings.json" as const;

export const MAX_CHARGE_ITEM = {
	itemId: 70,
	value: 500
} as const;

export const PAINT_CHARGE_ITEM = {
	itemId: 80,
	value: 500
} as const;

export const FLAG_ITEM = {
	itemId: 110,
	value: 20_000
} as const;

export const DEFAULT_APP_SETTINGS: SettingFields = {
	bulkOperationCooldown: 5000,
	paintMethod: "linear",
	accountTurnCooldown: 5000,
	chargeThreshold: 90
}

export const LOG_LEVEL_STYLES: Record<
	LogLevel, 
	{ color: ChalkInstance, icon: string }
> = {
	error: {
		color: chalk.red,
		icon: "✖"
	},
	warn: {
		color: chalk.hex("#FFA500"),
		icon: "⚠"
	},
	success: {
		color: chalk.green,
		icon: "✔"
	},
	info: {
		color: chalk.white,
		icon: "ℹ"
	},
	log: {
		color: chalk.gray,
		icon: "○"
	},
	debug: {
		color: chalk.yellow,
		icon: "⚙"
	}
}


export const WPLACE_PALLETE: Record<number, ColorInformation> = {
	0: { name: "Transparent", rgba: [0, 0, 0, 0], premium: false },
	1: { name: "Black", rgba: [0, 0, 0, 255], premium: false },
	2: { name: "Dark Gray", rgba: [60, 60, 60, 255], premium: false },
	3: { name: "Gray", rgba: [120, 120, 120, 255], premium: false },
	4: { name: "Light Gray", rgba: [210, 210, 210, 255], premium: false },
	5: { name: "White", rgba: [255, 255, 255, 255], premium: false },
	6: { name: "Deep Red", rgba: [96, 0, 24, 255], premium: false },
	7: { name: "Red", rgba: [237, 28, 36, 255], premium: false },
	8: { name: "Orange", rgba: [255, 127, 39, 255], premium: false },
	9: { name: "Gold", rgba: [246, 170, 9, 255], premium: false },
	10: { name: "Yellow", rgba: [249, 221, 59, 255], premium: false },
	11: { name: "Light Yellow", rgba: [255, 250, 188, 255], premium: false },
	12: { name: "Dark Green", rgba: [14, 185, 104, 255], premium: false },
	13: { name: "Green", rgba: [19, 230, 123, 255], premium: false },
	14: { name: "Light Green", rgba: [135, 255, 94, 255], premium: false },
	15: { name: "Dark Teal", rgba: [12, 129, 110, 255], premium: false },
	16: { name: "Teal", rgba: [16, 174, 166, 255], premium: false },
	17: { name: "Light Teal", rgba: [19, 225, 190, 255], premium: false },
	18: { name: "Dark Blue", rgba: [40, 80, 158, 255], premium: false },
	19: { name: "Blue", rgba: [64, 147, 228, 255], premium: false },
	20: { name: "Cyan", rgba: [96, 247, 242, 255], premium: false },
	21: { name: "Indigo", rgba: [107, 80, 246, 255], premium: false },
	22: { name: "Light Indigo", rgba: [153, 177, 251, 255], premium: false },
	23: { name: "Dark Purple", rgba: [120, 12, 153, 255], premium: false },
	24: { name: "Purple", rgba: [170, 56, 185, 255], premium: false },
	25: { name: "Light Purple", rgba: [224, 159, 249, 255], premium: false },
	26: { name: "Dark Pink", rgba: [203, 0, 122, 255], premium: false },
	27: { name: "Pink", rgba: [236, 31, 128, 255], premium: false },
	28: { name: "Light Pink", rgba: [243, 141, 169, 255], premium: false },
	29: { name: "Dark Brown", rgba: [104, 70, 52, 255], premium: false },
	30: { name: "Brown", rgba: [149, 104, 42, 255], premium: false },
	31: { name: "Beige", rgba: [248, 178, 119, 255], premium: false },
	32: { name: "Medium Gray", rgba: [170, 170, 170, 255], premium: true },
	33: { name: "Dark Red", rgba: [165, 14, 30, 255], premium: true },
	34: { name: "Light Red", rgba: [250, 128, 114, 255], premium: true },
	35: { name: "Dark Orange", rgba: [228, 92, 26, 255], premium: true },
	36: { name: "Light Tan", rgba: [214, 181, 148, 255], premium: true },
	37: { name: "Dark Goldenrod", rgba: [156, 132, 49, 255], premium: true },
	38: { name: "Goldenrod", rgba: [197, 173, 49, 255], premium: true },
	39: { name: "Light Goldenrod", rgba: [232, 212, 95, 255], premium: true },
	40: { name: "Dark Olive", rgba: [74, 107, 58, 255], premium: true },
	41: { name: "Olive", rgba: [90, 148, 74, 255], premium: true },
	42: { name: "Light Olive", rgba: [132, 197, 115, 255], premium: true },
	43: { name: "Dark Cyan", rgba: [15, 121, 159, 255], premium: true },
	44: { name: "Light Cyan", rgba: [187, 250, 242, 255], premium: true },
	45: { name: "Light Blue", rgba: [125, 199, 255, 255], premium: true },
	46: { name: "Dark Indigo", rgba: [77, 49, 184, 255], premium: true },
	47: { name: "Dark Slate Blue", rgba: [74, 66, 132, 255], premium: true },
	48: { name: "Slate Blue", rgba: [122, 113, 196, 255], premium: true },
	49: { name: "Light Slate Blue", rgba: [181, 174, 241, 255], premium: true },
	50: { name: "Light Brown", rgba: [219, 164, 99, 255], premium: true },
	51: { name: "Dark Beige", rgba: [209, 128, 81, 255], premium: true },
	52: { name: "Light Beige", rgba: [255, 197, 165, 255], premium: true },
	53: { name: "Dark Peach", rgba: [155, 82, 73, 255], premium: true },
	54: { name: "Peach", rgba: [209, 128, 120, 255], premium: true },
	55: { name: "Light Peach", rgba: [250, 182, 164, 255], premium: true },
	56: { name: "Dark Tan", rgba: [123, 99, 82, 255], premium: true },
	57: { name: "Tan", rgba: [156, 132, 107, 255], premium: true },
	58: { name: "Dark Slate", rgba: [51, 57, 65, 255], premium: true },
	59: { name: "Slate", rgba: [109, 117, 141, 255], premium: true },
	60: { name: "Light Slate", rgba: [179, 185, 209, 255], premium: true },
	61: { name: "Dark Stone", rgba: [109, 100, 63, 255], premium: true },
	62: { name: "Stone", rgba: [148, 140, 107, 255], premium: true },
	63: { name: "Light Stone", rgba: [205, 197, 158, 255], premium: true }
};
export const WPLACE_FLAGS = {
	1: { name: "Afghanistan", code: "AF", flag: "🇦🇫" },
	2: { name: "Albania", code: "AL", flag: "🇦🇱" },
	3: { name: "Algeria", code: "DZ", flag: "🇩🇿" },
	4: { name: "American Samoa", code: "AS", flag: "🇦🇸" },
	5: { name: "Andorra", code: "AD", flag: "🇦🇩" },
	6: { name: "Angola", code: "AO", flag: "🇦🇴" },
	7: { name: "Anguilla", code: "AI", flag: "🇦🇮" },
	8: { name: "Antarctica", code: "AQ", flag: "🇦🇶" },
	9: { name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬" },
	10: { name: "Argentina", code: "AR", flag: "🇦🇷" },
	11: { name: "Armenia", code: "AM", flag: "🇦🇲" },
	12: { name: "Aruba", code: "AW", flag: "🇦🇼" },
	13: { name: "Australia", code: "AU", flag: "🇦🇺" },
	14: { name: "Austria", code: "AT", flag: "🇦🇹" },
	15: { name: "Azerbaijan", code: "AZ", flag: "🇦🇿" },
	16: { name: "Bahamas", code: "BS", flag: "🇧🇸" },
	17: { name: "Bahrain", code: "BH", flag: "🇧🇭" },
	18: { name: "Bangladesh", code: "BD", flag: "🇧🇩" },
	19: { name: "Barbados", code: "BB", flag: "🇧🇧" },
	20: { name: "Belarus", code: "BY", flag: "🇧🇾" },
	21: { name: "Belgium", code: "BE", flag: "🇧🇪" },
	22: { name: "Belize", code: "BZ", flag: "🇧🇿" },
	23: { name: "Benin", code: "BJ", flag: "🇧🇯" },
	24: { name: "Bermuda", code: "BM", flag: "🇧🇲" },
	25: { name: "Bhutan", code: "BT", flag: "🇧🇹" },
	26: { name: "Bolivia", code: "BO", flag: "🇧🇴" },
	27: { name: "Bonaire", code: "BQ", flag: "🇧🇶" },
	28: { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦" },
	29: { name: "Botswana", code: "BW", flag: "🇧🇼" },
	30: { name: "Bouvet Island", code: "BV", flag: "🇧🇻" },
	31: { name: "Brazil", code: "BR", flag: "🇧🇷" },
	32: { name: "British Indian Ocean Territory", code: "IO", flag: "🇮🇴" },
	33: { name: "Brunei Darussalam", code: "BN", flag: "🇧🇳" },
	34: { name: "Bulgaria", code: "BG", flag: "🇧🇬" },
	35: { name: "Burkina Faso", code: "BF", flag: "🇧🇫" },
	36: { name: "Burundi", code: "BI", flag: "🇧🇮" },
	37: { name: "Cabo Verde", code: "CV", flag: "🇨🇻" },
	38: { name: "Cambodia", code: "KH", flag: "🇰🇭" },
	39: { name: "Cameroon", code: "CM", flag: "🇨🇲" },
	40: { name: "Canada", code: "CA", flag: "🇨🇦" },
	41: { name: "Cayman Islands", code: "KY", flag: "🇰🇾" },
	42: { name: "Central African Republic", code: "CF", flag: "🇨🇫" },
	43: { name: "Chad", code: "TD", flag: "🇹🇩" },
	44: { name: "Chile", code: "CL", flag: "🇨🇱" },
	45: { name: "China", code: "CN", flag: "🇨🇳" },
	46: { name: "Christmas Island", code: "CX", flag: "🇨🇽" },
	47: { name: "Cocos (Keeling) Islands", code: "CC", flag: "🇨🇨" },
	48: { name: "Colombia", code: "CO", flag: "🇨🇴" },
	49: { name: "Comoros", code: "KM", flag: "🇰🇲" },
	50: { name: "Congo", code: "CG", flag: "🇨🇬" },
	51: { name: "Cook Islands", code: "CK", flag: "🇨🇰" },
	52: { name: "Costa Rica", code: "CR", flag: "🇨🇷" },
	53: { name: "Croatia", code: "HR", flag: "🇭🇷" },
	54: { name: "Cuba", code: "CU", flag: "🇨🇺" },
	55: { name: "Curaçao", code: "CW", flag: "🇨🇼" },
	56: { name: "Cyprus", code: "CY", flag: "🇨🇾" },
	57: { name: "Czechia", code: "CZ", flag: "🇨🇿" },
	58: { name: "Côte d'Ivoire", code: "CI", flag: "🇨🇮" },
	59: { name: "Denmark", code: "DK", flag: "🇩🇰" },
	60: { name: "Djibouti", code: "DJ", flag: "🇩🇯" },
	61: { name: "Dominica", code: "DM", flag: "🇩🇲" },
	62: { name: "Dominican Republic", code: "DO", flag: "🇩🇴" },
	63: { name: "Ecuador", code: "EC", flag: "🇪🇨" },
	64: { name: "Egypt", code: "EG", flag: "🇪🇬" },
	65: { name: "El Salvador", code: "SV", flag: "🇸🇻" },
	66: { name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶" },
	67: { name: "Eritrea", code: "ER", flag: "🇪🇷" },
	68: { name: "Estonia", code: "EE", flag: "🇪🇪" },
	69: { name: "Eswatini", code: "SZ", flag: "🇸🇿" },
	70: { name: "Ethiopia", code: "ET", flag: "🇪🇹" },
	71: { name: "Falkland Islands (Malvinas)", code: "FK", flag: "🇫🇰" },
	72: { name: "Faroe Islands", code: "FO", flag: "🇫🇴" },
	73: { name: "Fiji", code: "FJ", flag: "🇫🇯" },
	74: { name: "Finland", code: "FI", flag: "🇫🇮" },
	75: { name: "France", code: "FR", flag: "🇫🇷" },
	76: { name: "French Guiana", code: "GF", flag: "🇬🇫" },
	77: { name: "French Polynesia", code: "PF", flag: "🇵🇫" },
	78: { name: "French Southern Territories", code: "TF", flag: "🇹🇫" },
	79: { name: "Gabon", code: "GA", flag: "🇬🇦" },
	80: { name: "Gambia", code: "GM", flag: "🇬🇲" },
	81: { name: "Georgia", code: "GE", flag: "🇬🇪" },
	82: { name: "Germany", code: "DE", flag: "🇩🇪" },
	83: { name: "Ghana", code: "GH", flag: "🇬🇭" },
	84: { name: "Gibraltar", code: "GI", flag: "🇬🇮" },
	85: { name: "Greece", code: "GR", flag: "🇬🇷" },
	86: { name: "Greenland", code: "GL", flag: "🇬🇱" },
	87: { name: "Grenada", code: "GD", flag: "🇬🇩" },
	88: { name: "Guadeloupe", code: "GP", flag: "🇬🇵" },
	89: { name: "Guam", code: "GU", flag: "🇬🇺" },
	90: { name: "Guatemala", code: "GT", flag: "🇬🇹" },
	91: { name: "Guernsey", code: "GG", flag: "🇬🇬" },
	92: { name: "Guinea", code: "GN", flag: "🇬🇳" },
	93: { name: "Guinea-Bissau", code: "GW", flag: "🇬🇼" },
	94: { name: "Guyana", code: "GY", flag: "🇬🇾" },
	95: { name: "Haiti", code: "HT", flag: "🇭🇹" },
	96: { name: "Heard Island and McDonald Islands", code: "HM", flag: "🇭🇲" },
	97: { name: "Honduras", code: "HN", flag: "🇭🇳" },
	98: { name: "Hong Kong", code: "HK", flag: "🇭🇰" },
	99: { name: "Hungary", code: "HU", flag: "🇭🇺" },
	100: { name: "Iceland", code: "IS", flag: "🇮🇸" },
	101: { name: "India", code: "IN", flag: "🇮🇳" },
	102: { name: "Indonesia", code: "ID", flag: "🇮🇩" },
	103: { name: "Iran", code: "IR", flag: "🇮🇷" },
	104: { name: "Iraq", code: "IQ", flag: "🇮🇶" },
	105: { name: "Ireland", code: "IE", flag: "🇮🇪" },
	106: { name: "Isle of Man", code: "IM", flag: "🇮🇲" },
	107: { name: "Israel", code: "IL", flag: "🇮🇱" },
	108: { name: "Italy", code: "IT", flag: "🇮🇹" },
	109: { name: "Jamaica", code: "JM", flag: "🇯🇲" },
	110: { name: "Japan", code: "JP", flag: "🇯🇵" },
	111: { name: "Jersey", code: "JE", flag: "🇯🇪" },
	112: { name: "Jordan", code: "JO", flag: "🇯🇴" },
	113: { name: "Kazakhstan", code: "KZ", flag: "🇰🇿" },
	114: { name: "Kenya", code: "KE", flag: "🇰🇪" },
	115: { name: "Kiribati", code: "KI", flag: "🇰🇮" },
	116: { name: "Kosovo", code: "XK", flag: "🇽🇰" },
	117: { name: "Kuwait", code: "KW", flag: "🇰🇼" },
	118: { name: "Kyrgyzstan", code: "KG", flag: "🇰🇬" },
	119: { name: "Laos", code: "LA", flag: "🇱🇦" },
	120: { name: "Latvia", code: "LV", flag: "🇱🇻" },
	121: { name: "Lebanon", code: "LB", flag: "🇱🇧" },
	122: { name: "Lesotho", code: "LS", flag: "🇱🇸" },
	123: { name: "Liberia", code: "LR", flag: "🇱🇷" },
	124: { name: "Libya", code: "LY", flag: "🇱🇾" },
	125: { name: "Liechtenstein", code: "LI", flag: "🇱🇮" },
	126: { name: "Lithuania", code: "LT", flag: "🇱🇹" },
	127: { name: "Luxembourg", code: "LU", flag: "🇱🇺" },
	128: { name: "Macao", code: "MO", flag: "🇲🇴" },
	129: { name: "Madagascar", code: "MG", flag: "🇲🇬" },
	130: { name: "Malawi", code: "MW", flag: "🇲🇼" },
	131: { name: "Malaysia", code: "MY", flag: "🇲🇾" },
	132: { name: "Maldives", code: "MV", flag: "🇲🇻" },
	133: { name: "Mali", code: "ML", flag: "🇲🇱" },
	134: { name: "Malta", code: "MT", flag: "🇲🇹" },
	135: { name: "Marshall Islands", code: "MH", flag: "🇲🇭" },
	136: { name: "Martinique", code: "MQ", flag: "🇲🇶" },
	137: { name: "Mauritania", code: "MR", flag: "🇲🇷" },
	138: { name: "Mauritius", code: "MU", flag: "🇲🇺" },
	139: { name: "Mayotte", code: "YT", flag: "🇾🇹" },
	140: { name: "Mexico", code: "MX", flag: "🇲🇽" },
	141: { name: "Micronesia", code: "FM", flag: "🇫🇲" },
	142: { name: "Moldova", code: "MD", flag: "🇲🇩" },
	143: { name: "Monaco", code: "MC", flag: "🇲🇨" },
	144: { name: "Mongolia", code: "MN", flag: "🇲🇳" },
	145: { name: "Montenegro", code: "ME", flag: "🇲🇪" },
	146: { name: "Montserrat", code: "MS", flag: "🇲🇸" },
	147: { name: "Morocco", code: "MA", flag: "🇲🇦" },
	148: { name: "Mozambique", code: "MZ", flag: "🇲🇿" },
	149: { name: "Myanmar", code: "MM", flag: "🇲🇲" },
	150: { name: "Namibia", code: "NA", flag: "🇳🇦" },
	151: { name: "Nauru", code: "NR", flag: "🇳🇷" },
	152: { name: "Nepal", code: "NP", flag: "🇳🇵" },
	153: { name: "Netherlands", code: "NL", flag: "🇳🇱" },
	154: { name: "New Caledonia", code: "NC", flag: "🇳🇨" },
	155: { name: "New Zealand", code: "NZ", flag: "🇳🇿" },
	156: { name: "Nicaragua", code: "NI", flag: "🇳🇮" },
	157: { name: "Niger", code: "NE", flag: "🇳🇪" },
	158: { name: "Nigeria", code: "NG", flag: "🇳🇬" },
	159: { name: "Niue", code: "NU", flag: "🇳🇺" },
	160: { name: "Norfolk Island", code: "NF", flag: "🇳🇫" },
	161: { name: "North Korea", code: "KP", flag: "🇰🇵" },
	162: { name: "North Macedonia", code: "MK", flag: "🇲🇰" },
	163: { name: "Northern Mariana Islands", code: "MP", flag: "🇲🇵" },
	164: { name: "Norway", code: "NO", flag: "🇳🇴" },
	165: { name: "Oman", code: "OM", flag: "🇴🇲" },
	166: { name: "Pakistan", code: "PK", flag: "🇵🇰" },
	167: { name: "Palau", code: "PW", flag: "🇵🇼" },
	168: { name: "Palestine", code: "PS", flag: "🇵🇸" },
	169: { name: "Panama", code: "PA", flag: "🇵🇦" },
	170: { name: "Papua New Guinea", code: "PG", flag: "🇵🇬" },
	171: { name: "Paraguay", code: "PY", flag: "🇵🇾" },
	172: { name: "Peru", code: "PE", flag: "🇵🇪" },
	173: { name: "Philippines", code: "PH", flag: "🇵🇭" },
	174: { name: "Pitcairn", code: "PN", flag: "🇵🇳" },
	175: { name: "Poland", code: "PL", flag: "🇵🇱" },
	176: { name: "Portugal", code: "PT", flag: "🇵🇹" },
	177: { name: "Puerto Rico", code: "PR", flag: "🇵🇷" },
	178: { name: "Qatar", code: "QA", flag: "🇶🇦" },
	179: { name: "Republic of the Congo", code: "CD", flag: "🇨🇩" },
	180: { name: "Romania", code: "RO", flag: "🇷🇴" },
	181: { name: "Russia", code: "RU", flag: "🇷🇺" },
	182: { name: "Rwanda", code: "RW", flag: "🇷🇼" },
	183: { name: "Réunion", code: "RE", flag: "🇷🇪" },
	184: { name: "Saint Barthélemy", code: "BL", flag: "🇧🇱" },
	185: { name: "Saint Helena", code: "SH", flag: "🇸🇭" },
	186: { name: "Saint Kitts and Nevis", code: "KN", flag: "🇰🇳" },
	187: { name: "Saint Lucia", code: "LC", flag: "🇱🇨" },
	188: { name: "Saint Martin (French part)", code: "MF", flag: "🇲🇫" },
	189: { name: "Saint Pierre and Miquelon", code: "PM", flag: "🇵🇲" },
	190: { name: "Saint Vincent and the Grenadines", code: "VC", flag: "🇻🇨" },
	191: { name: "Samoa", code: "WS", flag: "🇼🇸" },
	192: { name: "San Marino", code: "SM", flag: "🇸🇲" },
	193: { name: "Sao Tome and Principe", code: "ST", flag: "🇸🇹" },
	194: { name: "Saudi Arabia", code: "SA", flag: "🇸🇦" },
	195: { name: "Senegal", code: "SN", flag: "🇸🇳" },
	196: { name: "Serbia", code: "RS", flag: "🇷🇸" },
	197: { name: "Seychelles", code: "SC", flag: "🇸🇨" },
	198: { name: "Sierra Leone", code: "SL", flag: "🇸🇱" },
	199: { name: "Singapore", code: "SG", flag: "🇸🇬" },
	200: { name: "Sint Maarten (Dutch part)", code: "SX", flag: "🇸🇽" },
	201: { name: "Slovakia", code: "SK", flag: "🇸🇰" },
	202: { name: "Slovenia", code: "SI", flag: "🇸🇮" },
	203: { name: "Solomon Islands", code: "SB", flag: "🇸🇧" },
	204: { name: "Somalia", code: "SO", flag: "🇸🇴" },
	205: { name: "South Africa", code: "ZA", flag: "🇿🇦" },
	206: { name: "South Georgia and the South Sandwich Islands", code: "GS", flag: "🇬🇸" },
	207: { name: "South Korea", code: "KR", flag: "🇰🇷" },
	208: { name: "South Sudan", code: "SS", flag: "🇸🇸" },
	209: { name: "Spain", code: "ES", flag: "🇪🇸" },
	210: { name: "Sri Lanka", code: "LK", flag: "🇱🇰" },
	211: { name: "Sudan", code: "SD", flag: "🇸🇩" },
	212: { name: "Suriname", code: "SR", flag: "🇸🇷" },
	213: { name: "Svalbard and Jan Mayen", code: "SJ", flag: "🇸🇯" },
	214: { name: "Sweden", code: "SE", flag: "🇸🇪" },
	215: { name: "Switzerland", code: "CH", flag: "🇨🇭" },
	216: { name: "Syrian Arab Republic", code: "SY", flag: "🇸🇾" },
	217: { name: "Taiwan", code: "TW", flag: "🇹🇼" },
	218: { name: "Tajikistan", code: "TJ", flag: "🇹🇯" },
	219: { name: "Tanzania", code: "TZ", flag: "🇹🇿" },
	220: { name: "Thailand", code: "TH", flag: "🇹🇭" },
	221: { name: "Timor-Leste", code: "TL", flag: "🇹🇱" },
	222: { name: "Togo", code: "TG", flag: "🇹🇬" },
	223: { name: "Tokelau", code: "TK", flag: "🇹🇰" },
	224: { name: "Tonga", code: "TO", flag: "🇹🇴" },
	225: { name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹" },
	226: { name: "Tunisia", code: "TN", flag: "🇹🇳" },
	227: { name: "Turkmenistan", code: "TM", flag: "🇹🇲" },
	228: { name: "Turks and Caicos Islands", code: "TC", flag: "🇹🇨" },
	229: { name: "Tuvalu", code: "TV", flag: "🇹🇻" },
	230: { name: "Türkiye", code: "TR", flag: "🇹🇷" },
	231: { name: "Uganda", code: "UG", flag: "🇺🇬" },
	232: { name: "Ukraine", code: "UA", flag: "🇺🇦" },
	233: { name: "United Arab Emirates", code: "AE", flag: "🇦🇪" },
	234: { name: "United Kingdom", code: "GB", flag: "🇬🇧" },
	235: { name: "United States", code: "US", flag: "🇺🇸" },
	236: { name: "United States Minor Outlying Islands", code: "UM", flag: "🇺🇲" },
	237: { name: "Uruguay", code: "UY", flag: "🇺🇾" },
	238: { name: "Uzbekistan", code: "UZ", flag: "🇺🇿" },
	239: { name: "Vanuatu", code: "VU", flag: "🇻🇺" },
	240: { name: "Vatican City", code: "VA", flag: "🇻🇦" },
	241: { name: "Venezuela", code: "VE", flag: "🇻🇪" },
	242: { name: "Viet Nam", code: "VN", flag: "🇻🇳" },
	243: { name: "Virgin Islands", code: "VG", flag: "🇻🇬" },
	244: { name: "Virgin Islands", code: "VI", flag: "🇻🇮" },
	245: { name: "Wallis and Futuna", code: "WF", flag: "🇼🇫" },
	246: { name: "Western Sahara", code: "EH", flag: "🇪🇭" },
	247: { name: "Yemen", code: "YE", flag: "🇾🇪" },
	248: { name: "Zambia", code: "ZM", flag: "🇿🇲" },
	249: { name: "Zimbabwe", code: "ZW", flag: "🇿🇼" },
	250: { name: "Åland Islands", code: "AX", flag: "🇦🇽" },
	251: { name: "Canary Islands", code: "IC", flag: "🇮🇨" }
} as const;